# Generated by Django 3.1.7 on 2021-04-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='productdetailcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='productdetailcart',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.usercoupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(through='carts.UserCoupon', to='users.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_detail',
            field=models.ManyToManyField(through='carts.ProductDetailCart', to='products.ProductDetail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
