# Generated by Django 3.2 on 2021-04-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='product_detail_cart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='product_detail_cart',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_detail'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.user_coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(through='carts.User_Coupon', to='users.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_detail',
            field=models.ManyToManyField(through='carts.Product_Detail_Cart', to='products.Product_Detail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
